{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "c4a1a4ea",
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Hi, my name is George. How may I help you today?\n",
      "\n",
      "Please select from the following: \n",
      "\n",
      "Enter 1 for Deposit\n",
      "Enter 2 for Withdrawal\n",
      "Enter 3 for Check Balance\n",
      "Enter 4 to Exit\n",
      "\n",
      "Current Balance: $95\n",
      "Selection: 4\n",
      "\n",
      "Thank you for the visit, see you later!\n"
     ]
    }
   ],
   "source": [
    "print(f\"Hi, my name is George. How may I help you today?\" )\n",
    "print()\n",
    "print(f\"Please select from the following: \")\n",
    "print()\n",
    "print(f\"Enter 1 for Deposit\\n\" \"Enter 2 for Withdrawal\\n\" \"Enter 3 for Check Balance\\n\" \"Enter 4 to Exit\")\n",
    "print()\n",
    "\n",
    "with open('george_write.txt') as f:\n",
    "    balance = f.read()\n",
    "    \n",
    "print(f\"Current Balance: ${balance}\") \n",
    "\n",
    "# main menu below\n",
    "\n",
    "\n",
    "while True:\n",
    "    try:\n",
    "        selection = int(input(\"Selection: \"))\n",
    "        assert selection <= 4 and selection >0\n",
    "    except ValueError:\n",
    "        print(\"Sorry, I didn't understand that. Please input a selection between 1 and 4.\")\n",
    "        continue\n",
    "    except AssertionError:\n",
    "        print(\"Sorry, I didn't understand that. Please input a selection between 1 and 4.\")\n",
    "        continue\n",
    "    else:\n",
    "        break\n",
    "\n",
    "# deposit function below\n",
    "\n",
    "if selection == 1:\n",
    "    deposit_amount = int(input(\"How much would you like to deposit? We don't care about pennies here. \"))\n",
    "    if deposit_amount >=0:\n",
    "        balance = int(balance) + deposit_amount\n",
    "        print()\n",
    "        print(f\"Your balance is: ${balance}\")\n",
    "        with open('george_write.txt', 'w') as f: #overwriting\n",
    "            f.write(str(balance))    \n",
    "          \n",
    "    if deposit_amount == str():\n",
    "        print(f\"Your input is not correct. Please input a number like this, 100: \")\n",
    "        \n",
    "# withdrawal function below\n",
    "\n",
    "if selection == 2:\n",
    "    withdrawal_amount = int(input(\"How much would you like to withdraw? We don't care about pennies here. \"))\n",
    "    if withdrawal_amount >=0:\n",
    "        balance = int(balance) - withdrawal_amount\n",
    "        print()\n",
    "        print(f\"Your balance is: ${balance}\")\n",
    "        with open('george_write.txt', 'w') as f: #overwriting\n",
    "            f.write(str(balance))\n",
    "\n",
    "    if withdrawal_amount == str():\n",
    "        print(f\"Your input is not correct. Please input a number like this, 100: \")\n",
    "\n",
    "# check balance function below\n",
    "print()\n",
    "if selection == 3:\n",
    "    print(f\"Your balance is: ${balance}\")\n",
    "    print()\n",
    "    print(f'Thank you, goodbye')\n",
    "# exit function below\n",
    "\n",
    "if selection == 4:\n",
    "    with open('george_write.txt', 'w') as f: # appending not overwriting\n",
    "        f.write(str(balance))\n",
    "    print('Thank you for the visit, see you later!')\n",
    "\n",
    "# answer = None \n",
    "# while answer not in (\"yes\", \"no\"): \n",
    "#     answer = str.lower((input(f\"Would you like to continue? \")))\n",
    "#     if answer == \"yes\":\n",
    "#         print('Grabbing your request now.')\n",
    "#     elif answer == \"no\": \n",
    "#         print('Thank you, goodbye')\n",
    "#     else: \n",
    "#         print(\"Sorry, I didn't understand that. Please input a Yes or a No.\")\n",
    "#         break"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "6749d27a",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "import os\n",
    "import subprocess\n",
    "\n",
    "def hard_exit(selection):\n",
    "    exit()\n",
    "\n",
    "def exit_function(selection):\n",
    "    answer = None \n",
    "    while answer not in (\"yes\", \"no\"): \n",
    "        answer = str.lower((input(f\"Would you like to continue? \")))\n",
    "        if answer == \"yes\":\n",
    "            print()\n",
    "            print('Grabbing your request now.')\n",
    "            main_menu(selection)\n",
    "        elif answer == \"no\": \n",
    "            print('Thank you, goodbye')\n",
    "        else: \n",
    "            print(\"Sorry, I didn't understand that. Please input a Yes or a No.\")\n",
    "            break\n",
    "\n",
    "def main_menu(selection): # establishing function to loop through\n",
    "    with open('george_write.txt') as f:\n",
    "        balance = f.read()\n",
    "    while True:\n",
    "        try:\n",
    "            selection = int(input(\"Selection: \"))\n",
    "            assert selection <= 4 and selection >0\n",
    "            if selection == 1:\n",
    "                deposit_amount = int(input(\"How much would you like to deposit? We don't care about pennies here. \"))\n",
    "                if deposit_amount >=0:\n",
    "                    balance = int(balance) + deposit_amount\n",
    "                    print()\n",
    "                    print(f\"Your balance is: ${balance}\")\n",
    "                    with open('george_write.txt', 'w') as f: #overwriting\n",
    "                        f.write(str(balance))\n",
    "                    exit_function(selection)\n",
    "                    \n",
    "                if deposit_amount == str():\n",
    "                    print(f\"Your input is not correct. Please input a number like this, 100: \")\n",
    "            \n",
    "            if selection == 2:\n",
    "                withdrawal_amount = int(input(\"How much would you like to withdraw? We don't care about pennies here. \"))\n",
    "                if withdrawal_amount >=0:\n",
    "                    balance = int(balance) - withdrawal_amount\n",
    "                    print()\n",
    "                    print(f\"Your balance is: ${balance}\")\n",
    "                    with open('george_write.txt', 'w') as f: #overwriting\n",
    "                        f.write(str(balance))\n",
    "                    exit_function(selection)\n",
    "\n",
    "                if withdrawal_amount == str():\n",
    "                    print(f\"Your input is not correct. Please input a number like this, 100: \")\n",
    "\n",
    "            if selection == 3:\n",
    "                print(f\"Your balance is: ${balance}\")\n",
    "                print()\n",
    "                exit_function(selection)\n",
    "\n",
    "            if selection == 4:\n",
    "                with open('george_write.txt', 'w') as f: # appending not overwriting\n",
    "                    f.write(str(balance))\n",
    "                print('Thank you for the visit, see you later!')\n",
    "                hard_exit(selection)\n",
    "                \n",
    "        except ValueError:\n",
    "            print(\"Sorry, I didn't understand that. Please input a selection between 1 and 4.\")\n",
    "            continue\n",
    "        except AssertionError:\n",
    "            print(\"Sorry, I didn't understand that. Please input a selection between 1 and 4.\")\n",
    "            continue\n",
    "        else:\n",
    "            break"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "64321dd9",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "print(f\"Hi, my name is George. How may I help you today?\" )\n",
    "print()\n",
    "print(f\"Please select from the following: \")\n",
    "print()\n",
    "print(f\"Enter 1 for Deposit\\n\" \"Enter 2 for Withdrawal\\n\" \"Enter 3 for Check Balance\\n\" \"Enter 4 to Exit\")\n",
    "print()\n",
    "\n",
    "with open('george_write.txt') as f:\n",
    "    balance = f.read()\n",
    "    \n",
    "print(f\"Current Balance: ${balance}\") \n",
    "\n",
    "# main menu below\n",
    "\n",
    "while True:\n",
    "    try:\n",
    "        selection = int(input(\"Selection: \"))\n",
    "        assert selection <= 4 and selection >0\n",
    "    except ValueError:\n",
    "        print(\"Sorry, I didn't understand that. Please input a selection between 1 and 4.\")\n",
    "        continue\n",
    "    except AssertionError:\n",
    "        print(\"Sorry, I didn't understand that. Please input a selection between 1 and 4.\")\n",
    "        continue\n",
    "    else:\n",
    "        break\n",
    "\n",
    "# deposit function below\n",
    "\n",
    "if selection == 1:\n",
    "    deposit_amount = int(input(\"How much would you like to deposit? We don't care about pennies here. \"))\n",
    "    if deposit_amount >=0:\n",
    "        balance = int(balance) + deposit_amount\n",
    "        print()\n",
    "        print(f\"Your balance is: ${balance}\")\n",
    "        with open('george_write.txt', 'w') as f: #overwriting\n",
    "            f.write(str(balance))    \n",
    "        exit_function(selection)\n",
    "        \n",
    "    if deposit_amount == str():\n",
    "        print(f\"Your input is not correct. Please input a number like this, 100: \")\n",
    "        \n",
    "# withdrawal function below\n",
    "\n",
    "if selection == 2:\n",
    "    withdrawal_amount = int(input(\"How much would you like to withdraw? We don't care about pennies here. \"))\n",
    "    if withdrawal_amount >=0:\n",
    "        balance = int(balance) - withdrawal_amount\n",
    "        print()\n",
    "        print(f\"Your balance is: ${balance}\")\n",
    "        with open('george_write.txt', 'w') as f: #overwriting\n",
    "            f.write(str(balance))\n",
    "        exit_function(selection)\n",
    "        \n",
    "    if withdrawal_amount == str():\n",
    "        print(f\"Your input is not correct. Please input a number like this, 100: \")\n",
    "    \n",
    "# check balance function below\n",
    "\n",
    "print()\n",
    "if selection == 3:\n",
    "    print(f\"Your balance is: ${balance}\")\n",
    "    print()\n",
    "    print(f'Thank you, goodbye')\n",
    "    exit_function(selection)\n",
    "\n",
    "# exit function below\n",
    "\n",
    "if selection == 4:\n",
    "    with open('george_write.txt', 'w') as f: # appending not overwriting\n",
    "        f.write(str(balance))\n",
    "    print('Thank you for the visit, see you later!')\n",
    "    exit_function(selection)\n",
    "\n",
    "answer = None \n",
    "while answer not in (\"yes\", \"no\"): \n",
    "    answer = str.lower((input(f\"Would you like to continue? \")))\n",
    "    if answer == \"yes\":\n",
    "        print()\n",
    "        print('Grabbing your request now.')\n",
    "    elif answer == \"no\": \n",
    "        print('Thank you, goodbye')\n",
    "    else: \n",
    "        print(\"Sorry, I didn't understand that. Please input a Yes or a No.\")\n",
    "        break"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "28484869",
   "metadata": {},
   "source": [
    "* test success for looping through function 1, while may be messy and longwinded\n",
    "* test success for looping through all\n",
    "    * got stuck on function 4 to exit - kept asking for selection\n",
    "* test passed\n",
    "    * notebook is complete\n",
    "        * some minor bugs, like being asked twice but good for my first time!"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
